#!/bin/bash
pipeline 
{
    agent any
    tools {
                jdk "JDKDefault"
                maven "MavenDefault"
            }

    stages 
    {
        stage('Start') 
        {
            steps 
            {
                echo 'Project starts from here...!!!!'
            }
        }
        stage('Checkout')
        {
            steps
            {
                checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ishalinigupta/Jenkins-Project.git']]]
            }
        }
        stage('Build')
        {
            steps
            {
                bat "mvn clean"
            }
        }
        stage('Package')
        {
            steps
            {
                bat "mvn package"
            }
        }
        stage('Uploading Jar file to Nexus Repository')
        {
            steps
            {
                nexusArtifactUploader artifacts: [
                    [
                        artifactId: 'jenkins', 
                        classifier: '', 
                        file: 'target/jenkins-0.0.1-SNAPSHOT.jar', 
                        type: 'jar'
                    ]
                ], 
                credentialsId: 'nexus3', 
                groupId: 'demoproject', 
                nexusUrl: 'localhost:8081', 
                nexusVersion: 'nexus3', 
                protocol: 'http', 
                repository: 'FinalPipeline', 
                version: '1.${BUILD_NUMBER}'
            }
        }
        stage('SonarQube Analysis')
        {
            steps{
                withSonarQubeEnv('SonarQubeDefault') {
                    bat 'mvn sonar:sonar -D sonar.login=0427bcd45c1bc01345fbc5189014f95ba8791507'
                }
            }
        }
        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
          }
        stage('Success')
        {
            steps
            {
                echo "Project Succeeded"
            }
        }
        
    }
}
